### ISSUE TITLE
DOS-style Line Endings

### ISSUE THREAD

**Issue by ecarver** [wilseypa/warped#8]
Recently a lot of DOS line endings have been introduced into the warped source. This makes it impossible for those of us who use branches to auto-merge with the master branch. Please use Unix-style line endings.

**Comment by ajalt** [comment]
Can you give an example of which files have had their line endings changed?

**Comment by ecarver** [comment]
I know I had to manually merge ThreadedTimeWarpSimulationManager.cpp from master into arm-fixes just now. Josh has had some trouble with this too, but I don't know which files specifically.

```
grep -rnIl "\r\n" src/ | sort -u | wc -l
```

tells me that 409 files have at least one DOS line ending, but some of those are probably third party.

**Comment by guptask** [comment]
grep -IUrl "^M" \* | grep -v tags
(^M = Ctrl-V Ctrl-M)
This should reveal the file names. I'm pasting the results below:

autom4te.cache/output.1
autom4te.cache/traces.1
autom4te.cache/output.0
autom4te.cache/traces.0
autom4te.cache/traces.2
autom4te.cache/output.2
configure.ac
m4/check_lib_mpich.m4
m4/ax_cxx_compile_stdcxx_11.m4
src/WarpedDebug.cpp
src/StateManagerFactory.cpp
src/WarpedDebug.h
src/SchedulingManagerFactory.cpp
src/WarpedConfig.h.in~
src/LockFreeList.h
src/WarpedConfig.h
src/WarpedConfig.h.in
src/ThreadedTimeWarpSimulationManager.cpp
src/SimulationObjectProxy.cpp
src/CommunicationManagerFactory.cpp
src/TimeWarpSimulationManager.cpp
src/DVFSManagerFactory.cpp
src/EventSetFactory.cpp
src/Makefile.am
src/SequentialSimulationManager.cpp
src/GVTManagerFactory.cpp
src/DistributedDVFSManager.cpp
src/DVFSManagerImplementationBase.cpp
src/OutputManagerFactory.cpp
src/SharedDVFSManager.cpp
src/TokenPassingTerminationManager.cpp
src/warped.h
src/OptFossilCollManagerFactory.cpp
thirdparty/metis/GKlib/Makefile.am
thirdparty/metis/libmetis/Makefile.am

**Comment by guptask** [comment]
Some files in the warped-models repo also have DOS line endings.

**Comment by ajalt** [comment]
@ecarver, there are only ~300 files in the source tree, so your count may be a tad high ;)

Anyway, my search agrees with @guptask's

```
$ ack -l '\r\n'
CommunicationManagerFactory.cpp
DistributedDVFSManager.cpp
DVFSManagerFactory.cpp
DVFSManagerImplementationBase.cpp
EventSetFactory.cpp
GVTManagerFactory.cpp
LockFreeList.h
Makefile.am
OptFossilCollManagerFactory.cpp
OutputManagerFactory.cpp
SchedulingManagerFactory.cpp
SequentialSimulationManager.cpp
SharedDVFSManager.cpp
SimulationObjectProxy.cpp
StateManagerFactory.cpp
ThreadedTimeWarpSimulationManager.cpp
TimeWarpSimulationManager.cpp
TokenPassingTerminationManager.cpp
warped.h
WarpedDebug.cpp
WarpedDebug.h
```

I'm going to do a bisect and see if I can see when this started.

**Comment by guptask** [comment]
I did a set ff=unix on the reported files and checked those in. Please check whether any DOS line endings are still present in the warped repo. I'll make the same change in the warped-models repo.

**Comment by guptask** [comment]
Same change complete for the warped-models repo.

**Comment by ajalt** [comment]
I added a .gitattributes file to both repositories (72a27c4 for this one) that forces Unix line endings on commit, so hopefully this won't happen in the future.
